### ISSUE TITLE
Cloudprint crashes after 60 minutes

### ISSUE THREAD

**Issue by rasmussolmer** [armooo/cloudprint#102]
I have been happy with this excelent cloudprint script for over a year, but have experienced issues since the merge to OAuth2.

My current issue is that the script dies after 60 minutes of operation. It looks like the authorization against google has timed out:

600.000054 seconds until next keepalive
<<<
600.000056 seconds until next keepalive
<<<
600.000053 seconds until next keepalive
<<<
600.000056 seconds until next keepalive
<<<
600.000051 seconds until next keepalive
485.709014 seconds until timeout
<<<
600.000052 seconds until next keepalive
183.920715 seconds until timeout
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.12', 'console_scripts', 'cloudprint')()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 505, in main
    process_jobs(cups_connection, cpp)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 403, in process_jobs
    printers = cpp.get_printers()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 204, in get_printers
    'proxy': self.auth.guid,
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by sylvandb** [comment]
I believe that is the same issue I fixed in my fork: https://github.com/sylvandb/cloudprint/commit/e02fa6bd16adcd45fd4ae3e6e4309b2207523858

**Comment by rasmussolmer** [comment]
Yes, your forked version works like a charm, sylvandb@e02fa6b. There is still issues with the daemon mode however.
