### ISSUE TITLE
SSL issues raspberry pi

### ISSUE THREAD

**Issue by giladbarkai** [armooo/cloudprint#118]
On a raspberry pi, with latest distribution of raspbian and all packages up-to-date, I'm getting an SSL error.

Execution and error:

root@raspberrypi:~# cloudprint
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.14', 'console_scripts', 'cloudprint')()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 587, in main
    auth.login(name, description, ppd)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 122, in login
    headers={'X-CloudPrint-Proxy': 'ArmoooIsAnOEM'},
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
root@raspberrypi:~# 

How I installed:

root@raspberrypi:~# pip install cloudprint
Downloading/unpacking cloudprint
  Downloading cloudprint-0.14.tar.gz
  Running setup.py egg_info for package cloudprint
    
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from cloudprint)
Requirement already satisfied (use --upgrade to upgrade): pycups in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Installing collected packages: cloudprint
  Running setup.py install for cloudprint
    
    Installing cloudprint script to /usr/local/bin
Successfully installed cloudprint
Cleaning up...

Appranetly it doesn't affect others - I have no idea what's special about my setup.
Please advise.

**Comment by davesteele** [comment]
The URL in your failure report looks like it has the answers

First, it says that Python 2.7.9 or newer fixes this. Python2.7.10 is in the Raspbian repository, and the version referenced in stable is 2.7.9. So, upgrading to Jessie should fix this.

Alternatively, it says you should be able to work around this with 'pip install pyopenssl ndg-httpsclient pyasn1'. That sounds simpler.
