### ISSUE TITLE
Centos 7 daemon not working correctly

### ISSUE THREAD

**Issue by rnichols430** [armooo/cloudprint#121]
I installed everything like this:
yum install python python-pip gcc python-devel cups-devel

pip install pycups argparse cloudprint[daemon]

pip install --upgrade cloudprint[daemon]
ran cloudprint, it finds the printers and works with a terminal window up.  I have tried putting the startup in the rc.d/rc.local and it won't kick off..  any ideas?
 cloudprint -d
Traceback (most recent call last):
  File "/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.14', 'console_scripts', 'cloudprint')()
  File "/usr/lib/python2.7/site-packages/cloudprint/cloudprint.py", line 610, in main
    timeout=5,
  File "/usr/lib/python2.7/site-packages/daemon/pidfile.py", line 43, in __init__
    super(TimeoutPIDLockFile, self).__init__(path, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
[root@fobbit CUPS-Cloud-Print]#

**Comment by davesteele** [comment]
Cloudprint 0.13 and higher is incompatible with python-daemon <2.0 (b39740d2a8e2922749c92514c458a51734).

Check that daemon and pidfile are up-to-date (http://permalink.gmane.org/gmane.linux.debian.devel.python.modules/22964).

**Comment by rnichols430** [comment]
Ok, how do I get a different python-daemon version? I have 2.10...

**Comment by davesteele** [comment]
Per the link, I'd imagine the fix would be 'pip install -U lockfile'.

**Comment by rnichols430** [comment]
ok, i did update on the lockfile, the dameon, still same errors....

thank you,
ryan nichols
