### ISSUE TITLE
requests>=2.7.0

### ISSUE THREAD

**Issue by geenweb** [armooo/cloudprint#122]
I followed all directions and believe I've I have all dependent packages installed. I get the following output. My apologies if this is user error. Thank you for any guidance. Gene

$ cloudprint
Traceback (most recent call last):
  File "/usr/bin/cloudprint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests>=2.7.0' distribution was not found and is required by cloudprint
$

**Comment by davesteele** [comment]
This is a known problem with older distribution releases. Try:

> sudo pip install -U requests

(The '-U' may not be needed)

Or, if you are in a Debian/Ubuntu-derivative environment, the [packaged version](http://davesteele.github.io/cloudprint-service/) solves the problem.

Armooo, I addressed this with [this patch](https://github.com/davesteele/cloudprint-service/blob/master/debian/patches/0007-Remove-version-on-setup.py-requests-depends.patch)

**Comment by geenweb** [comment]
David,

Thank you very much! I successfully installed the packaged version and
verified that the connector successfully installed the cloud printer (it
was listed on the google website). Again thanks!!

I just purchased a new Chromebook for my elderly Mom. It appears that her
wireless Brother printer is not compatible with Google cloud print (tried
everything I could find online with no luck). I have a old netbook lying
about unused and installed Lubuntu 15.10, the Brother print drivers, and
now cloudprint. My plan is just to leave this tiny netbook running aside of
her printer. I'm not too familiar with Daemons. Should I just put
"cloudprint -d" in the .bashrc? Any other suggestions?

This is awesome!

Happy Holidays,

Gene

**Comment by davesteele** [comment]
If you installed 'cloudprint-service', the daemon part is taken care of.

Note that the service version stores authentication information in a different place. Use cps-auth to establish.

Any further discussion on package-based issues should move to https://github.com/davesteele/cloudprint-service/issues
