### ISSUE TITLE
Error when running cloudprint : `cups.IPPError: (1030, u'Not Found')`

### ISSUE THREAD

**Issue by davigre** [armooo/cloudprint#123]
I'm trying to install for first time the 'cloudprint' package in a [pcduino3 nano](http://www.linksprite.com/linksprite-pcduino3-nano/) with a ubuntu image:

```
root@ubuntu:/etc/cups# uname -a
Linux ubuntu 3.4.79+ #2 SMP PREEMPT Fri Dec 5 17:23:11 CST 2014 armv7l armv7l armv7l GNU/Linux
```

I have a working CUPS 1.5.3 server with '`Browsable On`' line in `cupsd.conf` (I can print from a Windows 7 client and local ( `lp test.pdf` ) ).

I follow [Ben Chapmen steps](https://benjaminjchapman.wordpress.com/2011/07/05/google-cloud-print/), in resume (with `root` login)...
```
apt-get install python-pip
pip install cloudprint
pip install daemon
cloudprint -d
```

To complete the second line I need to install 2 packages (because compilation errors):

```
 apt-get install python-dev libcupsimage2-dev
```

But in the last line...

```
root@ubuntu:~/Documents# cloudprint -d
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.14', 'console_scripts', 'cloudprint')()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 586, in main
    ppd, description = get_printer_info(cups_connection, name)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 347, in get_printer_info
    ppd_path = cups_connection.getPPD(printer_name)
cups.IPPError: (1030, u'Not Found')
root@ubuntu:~/Documents#
```

The same when running it manual...

```
root@ubuntu:~/Documents# cloudprint -v
Setting DEBUG-level logging
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.14', 'console_scripts', 'cloudprint')()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 586, in main
    ppd, description = get_printer_info(cups_connection, name)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 347, in get_printer_info
    ppd_path = cups_connection.getPPD(printer_name)
cups.IPPError: (1030, u'Not Found')
root@ubuntu:~/Documents#
```

What can I do?

Thank you.

**Comment by davesteele** [comment]
That failure can be caused by a disabled CUPS service.

/sbin/service cupsd status

**Comment by davigre** [comment]
I got this...
```
root@ubuntu:~# /sbin/service cupsd status
-bash: /sbin/service: No such file or directory
root@ubuntu:~# service cupsd status
cupsd: unrecognized service
root@ubuntu:~# service cups status
cups start/running, process 2173
root@ubuntu:~# ps -ewwo pid,args | grep cup*
 2173 /usr/sbin/cupsd -F
 2269 grep --color=auto cup*
root@ubuntu:~#
```
I can print from Win 7 Client.

Any other idea? Thank you

**Comment by davesteele** [comment]
No. I wouldn't expect the packaged versions you help you out, either.

**Comment by davigre** [comment]
Ok, I will play with CUPS configuration options....

**Comment by davigre** [comment]
After hours of investigation I finally make it work this way...

[Installing](https://github.com/armooo/cloudprint/wiki/Installing)

**Comment by tanmay380** [comment]
Could you please tell, what did you change?

**Comment by davesteele** [comment]
The google cloud print service is discontinued.
