### ISSUE TITLE
Error when running cloudprint : ssl.SSLError ...

### ISSUE THREAD

**Issue by davigre** [armooo/cloudprint#125]
Trying to run cloudprint from 
-Hardware: [pcDuino3 Nano](http://www.linksprite.com/linksprite-pcduino3-nano/)
-Image: [Armbian 4.5 -Vanilla Debian Jessie 4.2.3](http://www.armbian.com/pcduino3/)

Working CUPS 1.7.3

'Cloudprint' package install command:
`apt-get install cloudprint`

Problem when running 'cloudprint'...:
```
root@pcduino3nano:/home# cloudprint
Google username: goousername
Password:
Traceback (most recent call last):
  File "/usr/sbin/cloudprintd", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-cmd')()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 496, in main
    sync_printers(cups_connection, cpp)
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 330, in sync_printers
    remote_printers = dict([(p.name, p) for p in cpp.get_printers()])
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 177, in get_printers
    r = self.get_rest()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 173, in get_rest
    auth = self.get_auth()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 99, in get_auth
    'application/x-www-form-urlencoded')
  File "/usr/share/cloudprint/cloudprint/rest.py", line 122, in post
    return self.rest_call('POST', path, data, content_type, headers, response_type)
  File "/usr/share/cloudprint/cloudprint/rest.py", line 82, in rest_call
    self._conn.request(verb, path, data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

What can I do? Thank's.

**Update...**

I also install the cloudprint-service package:
`apt-get install cloudprint-service`

It permits the following command:

`service cloudprintd login`

This is the log of that command...

```
root@pcduino3nano:~# service cloudprintd login
Accounts with 2 factor authentication require an application-specific password
Google username: goousername
Password:
Traceback (most recent call last):
  File "/usr/sbin/cloudprintd", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-cmd')()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 496, in main
    sync_printers(cups_connection, cpp)
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 330, in sync_printers
    remote_printers = dict([(p.name, p) for p in cpp.get_printers()])
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 177, in get_printers
    r = self.get_rest()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 173, in get_rest
    auth = self.get_auth()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 99, in get_auth
    'application/x-www-form-urlencoded')
  File "/usr/share/cloudprint/cloudprint/rest.py", line 122, in post
    return self.rest_call('POST', path, data, content_type, headers, response_type)
  File "/usr/share/cloudprint/cloudprint/rest.py", line 105, in rest_call
    raise REST.RESTException('REST Error', resp.status, data)
cloudprint.rest.RESTException: REST Error:404
Message: https://developers.google.com/accounts/docs/AuthForInstalledApps

root@pcduino3nano:~#
```

**Comment by davigre** [comment]
Forget `apt-get install cloudprint-service` and `apt-get install cloudprint`, I remove the packages:

`apt-get remove cloudprint-service`
`apt-get install cloudprint`

Then

`apt-get install python-pip`
`pip install cloudprint`

**Comment by davigre** [comment]
I make it work this way:

[Installing](https://github.com/armooo/cloudprint/wiki/Install-Process)

**Comment by davesteele** [comment]
If you ever run that process again, I'd be interested in seeing the output of 'pip install cloudprint' from Armbian.

**Comment by davesteele** [comment]
It appears that it was 'apt-get install python-pip' that fixed your environment. It pulls in OpenSSL.

**Comment by davigre** [comment]
I'm trying to step back to get to the original condition:

```
root@pcduino3nano:/etc/cups# pip uninstall python-daemon
Uninstalling python-daemon-2.1.0:
  /usr/local/lib/python2.7/dist-packages/daemon/__init__.py
  /usr/local/lib/python2.7/dist-packages/daemon/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/daemon/_metadata.py
  /usr/local/lib/python2.7/dist-packages/daemon/_metadata.pyc
  /usr/local/lib/python2.7/dist-packages/daemon/daemon.py
  /usr/local/lib/python2.7/dist-packages/daemon/daemon.pyc
  /usr/local/lib/python2.7/dist-packages/daemon/pidfile.py
  /usr/local/lib/python2.7/dist-packages/daemon/pidfile.pyc
  /usr/local/lib/python2.7/dist-packages/daemon/runner.py
  /usr/local/lib/python2.7/dist-packages/daemon/runner.pyc
  /usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0.dist-info/INSTALLER
  /usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0.dist-info/metadata.json
  /usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0.dist-info/version_info.json
Proceed (y/n)? y
  Successfully uninstalled python-daemon-2.1.0
root@pcduino3nano:/etc/cups# pip uninstall cloudprint
Uninstalling cloudprint-0.14:
  /usr/local/bin/cloudprint
  /usr/local/lib/python2.7/dist-packages/cloudprint-0.14.egg-info
  /usr/local/lib/python2.7/dist-packages/cloudprint/__init__.py
  /usr/local/lib/python2.7/dist-packages/cloudprint/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py
  /usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.pyc
  /usr/local/lib/python2.7/dist-packages/cloudprint/xmpp.py
  /usr/local/lib/python2.7/dist-packages/cloudprint/xmpp.pyc
Proceed (y/n)? y
  Successfully uninstalled cloudprint-0.14
root@pcduino3nano:/etc/cups# easy_install -m pip
Searching for pip
Best match: pip 8.0.2
Processing pip-8.0.2-py2.7.egg
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages/pip-8.0.2-py2.7.egg
Because this distribution was installed --multi-version, before you can
import modules from this package in an application, you will need to
'import pkg_resources' and then use a 'require()' call similar to one of
these examples, in order to select the desired version:

    pkg_resources.require("pip")  # latest installed version
    pkg_resources.require("pip==8.0.2")  # this exact version
    pkg_resources.require("pip>=8.0.2")  # this version or higher

Processing dependencies for pip
Finished processing dependencies for pip
```

Let's ignore this last fail and install the repository package:

```
root@pcduino3nano:/etc/cups# apt-get install cloudprint
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libftdi1 liblircclient0 python-chardet python-colorama python-distlib python-html5lib python-requests python-six python-urllib3
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  cloudprint
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.0 kB of archives.
After this operation, 108 kB of additional disk space will be used.
Get:1 http://httpredir.debian.org/debian/ jessie/main cloudprint all 0.11-5 [14.0 kB]
Fetched 14.0 kB in 1s (10.5 kB/s)
Selecting previously unselected package cloudprint.
(Reading database ... 53283 files and directories currently installed.)
Preparing to unpack .../cloudprint_0.11-5_all.deb ...
Unpacking cloudprint (0.11-5) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up cloudprint (0.11-5) ...
```
Running...

```
root@pcduino3nano:/usr/bin# ./cloudprint -c
Google username: googleuser
Password:
Traceback (most recent call last):
  File "./cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-cmd')()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 496, in main
    sync_printers(cups_connection, cpp)
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 330, in sync_printers
    remote_printers = dict([(p.name, p) for p in cpp.get_printers()])
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 177, in get_printers
    r = self.get_rest()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 173, in get_rest
    auth = self.get_auth()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 99, in get_auth
    'application/x-www-form-urlencoded')
  File "/usr/share/cloudprint/cloudprint/rest.py", line 122, in post
    return self.rest_call('POST', path, data, content_type, headers, response_type)
  File "/usr/share/cloudprint/cloudprint/rest.py", line 105, in rest_call
    raise REST.RESTException('REST Error', resp.status, data)
cloudprint.rest.RESTException: REST Error:404
Message: https://developers.google.com/accounts/docs/AuthForInstalledApps

root@pcduino3nano:/usr/bin#
```

Ok, and now lets try to make it the 'normal' [way](https://benjaminjchapman.wordpress.com/2011/07/05/google-cloud-print/) (without the repository packages):

```
root@pcduino3nano:/usr/bin# apt-get remove cloudprint
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libftdi1 liblircclient0 python-chardet python-colorama python-cups python-distlib python-html5lib python-pkg-resources python-requests python-setuptools python-six python-urllib3
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  cloudprint
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 108 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 53303 files and directories currently installed.)
Removing cloudprint (0.11-5) ...
Processing triggers for man-db (2.7.0.2-5) ...
root@pcduino3nano:/usr/bin#
```
```
root@pcduino3nano:/usr/bin# pip install cloudprint
Collecting cloudprint
  Downloading cloudprint-0.14.tar.gz
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from cloudprint)
Requirement already satisfied (use --upgrade to upgrade): pycups in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Installing collected packages: cloudprint
  Running setup.py install for cloudprint ... done
Successfully installed cloudprint-0.14
root@pcduino3nano:/usr# pip show cloudprint
---
Metadata-Version: 1.1
Name: cloudprint
Version: 0.14
Summary: Google cloud print proxy for linux/OSX
Home-page: https://github.com/armooo/cloudprint
Author: Jason Michalski
Author-email: armooo@armooo.net
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: argparse, pycups, requests
Entry-points:
  [console_scripts]
  cloudprint = cloudprint.cloudprint:main
root@pcduino3nano:/usr# pip show -f cloudprint
---
Metadata-Version: 1.1
Name: cloudprint
Version: 0.14
Summary: Google cloud print proxy for linux/OSX
Home-page: https://github.com/armooo/cloudprint
Author: Jason Michalski
Author-email: armooo@armooo.net
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: argparse, pycups, requests
Files:
  ../../../bin/cloudprint
  cloudprint-0.14-py2.7.egg-info
  cloudprint-0.14-py2.7.egg-info/PKG-INFO
  cloudprint-0.14-py2.7.egg-info/SOURCES.txt
  cloudprint-0.14-py2.7.egg-info/dependency_links.txt
  cloudprint-0.14-py2.7.egg-info/entry_points.txt
  cloudprint-0.14-py2.7.egg-info/requires.txt
  cloudprint-0.14-py2.7.egg-info/top_level.txt
  cloudprint/__init__.py
  cloudprint/__init__.pyc
  cloudprint/cloudprint.py
  cloudprint/cloudprint.pyc
  cloudprint/xmpp.py
  cloudprint/xmpp.pyc
Entry-points:
  [console_scripts]
  cloudprint = cloudprint.cloudprint:main
```
`cloudprint` work's again!!!

I only need that `clouprintd` (respository daemon that starts cloudprint) work for this version.

**Comment by davesteele** [comment]
I appreciate the work you did here. I see that the real problem is that the version of cloudprint in the repository you are linked to is broken. See http://davesteele.github.io/cloudprint-service/

Thanks again.
