### ISSUE TITLE
cups.IPPError: (1030, u'Not Found')

### ISSUE THREAD

**Issue by rickrich** [armooo/cloudprint#126]
I have used this before, but I upgraded to Fedora 22 and now I get this error:

$ sudo pip install cloudprint
[sudo] password for rick: 
Requirement already satisfied (use --upgrade to upgrade): cloudprint in /usr/lib/python2.7/site-packages/cloudprint-0.14-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7/site-packages/argparse-1.4.0-py2.7.egg (from cloudprint)
Requirement already satisfied (use --upgrade to upgrade): pycups in /usr/lib64/python2.7/site-packages (from cloudprint)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/lib/python2.7/site-packages (from cloudprint)
Requirement already satisfied (use --upgrade to upgrade): urllib3==1.13.1 in /usr/lib/python2.7/site-packages (from requests>=2.7.0->cloudprint)

$ cloudprint
Traceback (most recent call last):
  File "/usr/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.14', 'console_scripts', 'cloudprint')()
  File "build/bdist.linux-x86_64/egg/cloudprint/cloudprint.py", line 604, in main
  File "build/bdist.linux-x86_64/egg/cloudprint/cloudprint.py", line 356, in get_printer_info
cups.IPPError: (1030, u'Not Found')

Any help???

**Comment by rickrich** [comment]
CUPS is running, tho:

$ systemctl status cups
● cups.service - CUPS Scheduler
   Loaded: loaded (/usr/lib/systemd/system/cups.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2016-03-13 16:12:18 CDT; 3 days ago
     Docs: man:cupsd(8)
 Main PID: 18098 (cupsd)
   Status: "Scheduler is running..."
   CGroup: /system.slice/cups.service
           ├─18098 /usr/sbin/cupsd -l
           └─19280 /usr/lib/cups/notifier/dbus dbus://

**Comment by a-andreyev** [comment]
+1 same issue:
`$ systemctl status org.cups.cupsd.service`

```
* org.cups.cupsd.service - CUPS Scheduler
   Loaded: loaded (/usr/lib/systemd/system/org.cups.cupsd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-05-12 08:16:52 UTC; 2h 20min ago
     Docs: man:cupsd(8)
 Main PID: 255 (cupsd)
    Tasks: 2 (limit: 512)
   CGroup: /system.slice/org.cups.cupsd.service
           `-255 /usr/bin/cupsd -l

May 12 08:16:52 rpi2homehost systemd[1]: Started CUPS Scheduler.
```

**Comment by davesteele** [comment]
Printer(s) information? queue name and printer model?

**Comment by a-andreyev** [comment]
`$ lpstat -s`:

```
system default destination: HOME_SAMSUNG_SCX4200
device for HOME_SAMSUNG_SCX4200: usb://Samsung/SCX-4200%20Series?serial=8T66BFGQ701222F.
```


`$ lpstat -p HOME_SAMSUNG_SCX4200`:

```
printer HOME_SAMSUNG_SCX4200 is idle.  enabled since Fri Feb 26 13:46:38 2016
```

**Comment by davesteele** [comment]
Nothing obvious there.

**Comment by a-andreyev** [comment]
I'm sorry! My problem fixed when I've reinstalled my printer via cups (guess something was wrong in the printer description). Not sure what was wrong, probably PDD driver was not selected, but now it's ok.
Thank you!

**Comment by rickrich** [comment]
$ root pip uninstall cloudprint
The directory '/home/rick/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Cannot uninstall requirement cloudprint, not installed
The directory '/home/rick/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

$ root pip install cloudprint
The directory '/home/rick/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/rick/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting cloudprint
  Downloading cloudprint-0.14.tar.gz
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7/site-packages/argparse-1.4.0-py2.7.egg (from cloudprint)
Requirement already satisfied (use --upgrade to upgrade): pycups in /usr/lib64/python2.7/site-packages (from cloudprint)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/lib/python2.7/site-packages (from cloudprint)
Installing collected packages: cloudprint
  Running setup.py install for cloudprint ... done
Successfully installed cloudprint-0.14

$ cloudprint -i p1505n
Traceback (most recent call last):
  File "/usr/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.14', 'console_scripts', 'cloudprint')()
  File "/usr/lib/python2.7/site-packages/cloudprint/cloudprint.py", line 586, in main
    ppd, description = get_printer_info(cups_connection, name)
  File "/usr/lib/python2.7/site-packages/cloudprint/cloudprint.py", line 347, in get_printer_info
    ppd_path = cups_connection.getPPD(printer_name)
cups.IPPError: (1030, u'Not Found')

$ lpstat -a p1505n
p1505n accepting requests since Sun 25 Jan 2015 01:07:58 PM CST

$ lpstat -p p1505n
printer p1505n is idle.  enabled since Sun 25 Jan 2015 01:07:58 PM CST

$ systemctl status cups
● cups.service - CUPS Scheduler
   Loaded: loaded (/usr/lib/systemd/system/cups.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2016-05-07 06:27:08 CDT; 5 days ago
     Docs: man:cupsd(8)
 Main PID: 1658 (cupsd)
   Status: "Scheduler is running..."
   CGroup: /system.slice/cups.service
           ├─ 1658 /usr/sbin/cupsd -l
           └─29377 /usr/lib/cups/notifier/dbus dbus://

No dice here, though!  Should I install Google's Chrome ???

**Comment by davesteele** [comment]
There's also a Go client.

**Comment by rickrich** [comment]
Thanks!  https://github.com/google/cups-connector/wiki/Install did the trick.  Sorry, Jason.

**Comment by valiafetisov** [comment]
For me, the `cups.IPPError: (1030, u'Not Found')` problem was that CUPS ppd folder (`/usr/share/cups/model`) had two different drivers for the same printer model I was using. So the line

https://github.com/armooo/cloudprint/blob/108b9f02669e141a499e339ed6bf098c5553dabc/cloudprint/cloudprint.py#L356

located at `/usr/share/cloudprint/cloudprint/cloudprint.py:372` was throwing the error.
I deleted unused driver and the problem was solved.
