### ISSUE TITLE
Cloud print crashes when print job sent

### ISSUE THREAD

**Issue by robert-s** [armooo/cloudprint#33]
When I start cloudprint it runs until I send a print job.  Here is the message:

 # python2.7 /usr/lib/cloudprint/cloudprint.py
Updated Printer MFC-7420
Updated Printer CUPS-PDF
Traceback (most recent call last):
  File "/usr/lib/cloudprint/cloudprint.py", line 388, in <module>
    main()
  File "/usr/lib/cloudprint/cloudprint.py", line 384, in main
    process_jobs(cups_connection, cpp, printers)
  File "/usr/lib/cloudprint/cloudprint.py", line 314, in process_jobs
    process_job(cups_connection, cpp, printer, job)
  File "/usr/lib/cloudprint/cloudprint.py", line 307, in process_job
    cpp.fail_job(job['id'])
  File "/usr/lib/cloudprint/cloudprint.py", line 224, in fail_job
    { 'X-CloudPrint-Proxy' : 'ArmoooIsAnOEM' },
  File "/usr/lib/cloudprint/cloudprint.py", line 107, in f
    r = attr(*arg, **karg)
  File "/usr/lib64/cloudprint/rest.py", line 105, in post
    return self.rest_call('POST', path, data, content_type, headers, response_type)
  File "/usr/lib64/cloudprint/rest.py", line 88, in rest_call
    raise REST.RESTException('REST Error', resp.status, data)
rest.RESTException: REST Error:500
Message: <HTML>
<HEAD>
<TITLE>Internal Server Error</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Internal Server Error</H1>
<H2>Error 500</H2>
</BODY>
</HTML>

**Comment by armooo** [comment]
If this is still happening please reopen.
