### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by bitloggerig** [armooo/cloudprint#39]
Сloudprint outputs the following error when I'm trying to start it:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cloudprint-0.5-py2.7.egg/cloudprint/cloudprint.py", line 440, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint-0.5-py2.7.egg/cloudprint/cloudprint.py", line 408, in main
    sync_printers(cups_connection, cpp)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint-0.5-py2.7.egg/cloudprint/cloudprint.py", line 283, in sync_printers
    cpp.add_printer(printer_name, description, ppd)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint-0.5-py2.7.egg/cloudprint/cloudprint.py", line 169, in add_printer
    { 'X-CloudPrint-Proxy' : 'ArmoooIsAnOEM'},
  File "/usr/local/lib/python2.7/dist-packages/cloudprint-0.5-py2.7.egg/cloudprint/cloudprint.py", line 118, in f
    r = attr(*arg, **karg)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint-0.5-py2.7.egg/cloudprint/rest.py", line 105, in post
    return self.rest_call('POST', path, data, content_type, headers, response_type)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint-0.5-py2.7.egg/cloudprint/rest.py", line 58, in rest_call
    data = self.CONTENT_ENCODE[content_type](data)
  File "/usr/lib/python2.7/urllib.py", line 1312, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0421' in position 0: ordinal not in range(128)
```
I'm using the latest version from github on Ubuntu 12.10 64-bit.

**Comment by armooo** [comment]
Requests should correctly send a utf8 http request now. If this is still happening please reopen with a new stack trace.
