### ISSUE TITLE
cloudprint often fails to start

### ISSUE THREAD

**Issue by zoof** [armooo/cloudprint#56]
Not sure what the issue is but the following is the frequent output, whether it is being started from the command line, or as an init process.  Please let me know what further information I can provide.  I have cloudprint installed on a cubieboard running debian wheezy.

Starting Google Cloud Print: Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.10', 'console_scripts', 'cloudprint')()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 448, in main
    sync_printers(cups_connection, cpp)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 294, in sync_printers
    ppd_file = open(cups_connection.getPPD(printer_name))
cups.IPPError: (1030, 'client-error-not-found')

**Comment by armooo** [comment]
It sounds like cloudprint can not connect to your local cups server. Is this in an init script?

**Comment by davigre** [comment]
I'm trying to install for first time the 'cloudprint' package in a [pcduino3 nano](http://www.linksprite.com/linksprite-pcduino3-nano/) with an ubuntu image:

```
root@ubuntu:/etc/cups# uname -a
Linux ubuntu 3.4.79+ #2 SMP PREEMPT Fri Dec 5 17:23:11 CST 2014 armv7l armv7l armv7l GNU/Linux
```

I have a working CUPS 1.5.3 server with '`Browsable On`' line in `cupsd.conf` (I can print from a Windows 7 client and local ( `lp test.pdf` ) ).

I follow [Ben Chapmen steps](https://benjaminjchapman.wordpress.com/2011/07/05/google-cloud-print/), in resume...
```
sudo apt-get install python-pip
sudo pip install cloudprint
sudo pip install daemon
sudo cloudprint -d
```

To complete the second line I need to install 2 packages (because compilation errors):

```
 apt-get install python-dev libcupsimage2-dev
```

But in the last line...

```
root@ubuntu:~/Documents# cloudprint -d
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.14', 'console_scripts', 'cloudprint')()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 586, in main
    ppd, description = get_printer_info(cups_connection, name)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 347, in get_printer_info
    ppd_path = cups_connection.getPPD(printer_name)
cups.IPPError: (1030, u'Not Found')
```

The same when running it manual...

```
root@ubuntu:~/Documents# cloudprint -v
Setting DEBUG-level logging
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.14', 'console_scripts', 'cloudprint')()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 586, in main
    ppd, description = get_printer_info(cups_connection, name)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 347, in get_printer_info
    ppd_path = cups_connection.getPPD(printer_name)
cups.IPPError: (1030, u'Not Found')
```

What can I do?
