### ISSUE TITLE
Daemon mode crashes

### ISSUE THREAD

**Issue by billlagr** [armooo/cloudprint#83]
Hi..
I finally! got Cloudprint to work on my ARM based NAS. Starting it directly from the command line works fine, however if I start with -d I get -

bill@LS_NAS_1:/opt/local/bin# /opt/local/bin/cloudprint -d

Traceback (most recent call last):
  File "/opt/local/bin/cloudprint", line 8, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint')()
  File "build/bdist.linux-armv5tel/egg/cloudprint/cloudprint.py", line 498, in main
  File "/opt/local/lib/python2.7/site-packages/python_daemon-1.5.5-py2.7.egg/daemon/runner.py", line 25, in <module>
    import pidlockfile
  File "/opt/local/lib/python2.7/site-packages/python_daemon-1.5.5-py2.7.egg/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str

I'm not really sure where to look to fix this?
I'm using Python 2.7.3, python-daemon-1.5.5, lockfile 0.9.1

Thanks

*Edit - fixed my own problem, downgraded lockfile from 0.9.1 to 0.8 and seems to be working fine..

**Comment by armooo** [comment]
I have added a dependency on a version of python-daemon which should fix this problem. You can not install with `pip install cloudprint[daemon]`.
