### ISSUE TITLE
except rest.REST.RESTException, e:

### ISSUE THREAD

**Issue by jflaflamme** [armooo/cloudprint#90]
With the last version from git, I am on arch for RPi.

Same error with pip install version or with or without arguments to cloudprint.

```
Traceback (most recent call last):
  File "/usr/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint')()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2472, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2186, in load
    ['__name__'])
  File "/usr/lib/python3.4/site-packages/cloudprint/cloudprint.py", line 91
    except rest.REST.RESTException, e:
                                  ^
SyntaxError: invalid syntax
```

**Comment by armooo** [comment]
Correct currently only python2.6 and python2.7 are suported
