### ISSUE TITLE
'ascii' codec can't encode character u'\xe9' in position 17

### ISSUE THREAD

**Issue by ruilapa** [armooo/cloudprint#92]
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint')()
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 468, in main
    sync_printers(cups_connection, cpp)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 323, in sync_printers
    remote_printers[printer_name].update(description, ppd)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 272, in update
    return self.cpp.update_printer(self.id, self.name, description, ppd)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 213, in update_printer
    { 'X-CloudPrint-Proxy' : 'ArmoooIsAnOEM'},
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/cloudprint.py", line 141, in f
    r = attr(*arg, **karg)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/rest.py", line 105, in post
    return self.rest_call('POST', path, data, content_type, headers, response_type)
  File "/usr/local/lib/python2.7/dist-packages/cloudprint/rest.py", line 58, in rest_call
    data = self.CONTENT_ENCODE[content_type](data)
  File "/usr/lib/python2.7/urllib.py", line 1312, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 17: ordinal not in range(128)

**Comment by avlis** [comment]
It looks like a problem with accents on the printer description.
seems to be fixable with:

--- cloudprint.py.ori	2015-02-07 16:33:14.221313910 +0000
+++ cloudprint.py.fixed	2015-02-07 16:34:07.467312650 +0000
@@ -206,7 +206,7 @@
                 'capabilities' : ppd.encode('utf-8'),
                 'defaults' : ppd.encode('utf-8'),
                 'status' : 'OK',
-                'description' : description,
+                'description' : description.encode('utf-8'),
                 'capsHash' : hashlib.sha1(ppd.encode('utf-8')).hexdigest(),
             },
             'application/x-www-form-urlencoded',

**Comment by armooo** [comment]
This should be fixed now that we use requests to build http requests. If this still happens please reopen.
