### ISSUE TITLE
After installation  - cloudprint wont start

### ISSUE THREAD

**Issue by razzia23** [armooo/cloudprint#99]
Sorry - Solution:

pip install requests

Hello,

here is the output:

root@castle:/tmp/cloudprint-master# cloudprint -h
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/cloudprint-0.11-py2.7.egg/cloudprint/cloudprint.py", line 28, in <module>
    import requests
ImportError: No module named requests

How can I fix that? 

Best regards
Stephan

**Comment by armooo** [comment]
The new dependency on requests was not added to the setup.py. I just took care of it now.
